/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "telescope": [
        {
            "name": "view",
            "required": false
        }
    ],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "password.reset": [],
    "users.show": [
        {
            "name": "user",
            "required": true
        }
    ],
    "users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "wallets.index": [],
    "wallets.store": [],
    "wallets.show": [
        {
            "name": "wallet",
            "required": true,
            "binding": "id"
        }
    ],
    "wallets.update": [
        {
            "name": "wallet",
            "required": true,
            "binding": "id"
        }
    ],
    "wallets.destroy": [
        {
            "name": "wallet",
            "required": true,
            "binding": "id"
        }
    ],
    "payments.index": [],
    "payments.store": [],
    "payments.show": [
        {
            "name": "payment",
            "required": true,
            "binding": "id"
        }
    ],
    "payments.update": [
        {
            "name": "payment",
            "required": true,
            "binding": "id"
        }
    ],
    "payments.destroy": [
        {
            "name": "payment",
            "required": true,
            "binding": "id"
        }
    ],
    "payment_options.index": [],
    "payment_options.store": [],
    "payment_options.show": [
        {
            "name": "payment_option",
            "required": true
        }
    ],
    "payment_options.update": [
        {
            "name": "payment_option",
            "required": true
        }
    ],
    "payment_options.destroy": [
        {
            "name": "payment_option",
            "required": true
        }
    ],
    "plans.index": [],
    "plans.show": [
        {
            "name": "plan",
            "required": true,
            "binding": "id"
        }
    ],
    "savings.index": [],
    "savings.store": [],
    "savings.show": [
        {
            "name": "saving",
            "required": true,
            "binding": "id"
        }
    ],
    "savings.update": [
        {
            "name": "saving",
            "required": true,
            "binding": "id"
        }
    ],
    "savings.destroy": [
        {
            "name": "saving",
            "required": true,
            "binding": "id"
        }
    ],
    "user_accounts.index": [],
    "user_accounts.store": [],
    "user_accounts.show": [
        {
            "name": "user_account",
            "required": true
        }
    ],
    "user_accounts.update": [
        {
            "name": "user_account",
            "required": true
        }
    ],
    "user_accounts.destroy": [
        {
            "name": "user_account",
            "required": true
        }
    ],
    "transactions.index": [],
    "transactions.show": [
        {
            "name": "transaction",
            "required": true,
            "binding": "id"
        }
    ],
    "challenges.index": [],
    "challenges.store": [],
    "challenges.show": [
        {
            "name": "challenge",
            "required": true,
            "binding": "id"
        }
    ],
    "wallet_interests.index": [],
    "notifications.index": [],
    "notifications.show": [
        {
            "name": "notification",
            "required": true,
            "binding": "id"
        }
    ],
    "verifications.index": [],
    "verifications.store": [],
    "verifications.show": [
        {
            "name": "verification",
            "required": true,
            "binding": "id"
        }
    ],
    "verifications.update": [
        {
            "name": "verification",
            "required": true,
            "binding": "id"
        }
    ],
    "verifications.destroy": [
        {
            "name": "verification",
            "required": true,
            "binding": "id"
        }
    ],
    "transfers.index": [],
    "transfers.store": []
}
}
export {};
